apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - httproutes.yaml
  - minio-credentials.yml
  - servicemonitor.yaml
  - monitoring-secrets.yaml


helmCharts:
- name: kube-prometheus-stack
  namespace: monitoring
  repo: https://prometheus-community.github.io/helm-charts
  version: 82.3.0
  releaseName: kube-prometheus-stack
  valuesFile: prom-values.yaml
- name: victoria-logs-single 
  namespace: monitoring
  repo: https://victoriametrics.github.io/helm-charts 
  version: 0.11.28
  releaseName: victorialogs
  valuesFile: victoria-values.yaml