---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore # Must match SecretStore on the cluster
  target:
    name: monitoring-secrets # Name for the secret on the cluster
    creationPolicy: Owner
  dataFrom:
    - extract: 
        conversionStrategy: Default	
        decodingStrategy: None
        key: monitoring-secrets # Name in the OCI Vault
        metadataPolicy: None