cluster:
  apiServer:
    extraArgs:
      audit-log-path: /var/log/kubernetes/audit.log
      audit-log-maxage: "3"
      audit-log-maxbackup: "3"
      audit-log-maxsize: "50"
      audit-policy-file: /etc/kubernetes/audit-policy/audit-policy.yaml

machine:
  files:
    - content: |
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
          - level: None
            nonResourceURLs:
              - /healthz*
              - /readyz*
              - /livez*
              - /metrics
          - level: None
            verbs: ["watch"]
            resources:
              - group: ""
                resources: ["events"]
          - level: Metadata
            resources:
              - group: ""
                resources: ["secrets", "configmaps"]
          - level: Request
            resources:
              - group: "rbac.authorization.k8s.io"
          - level: Request
            verbs: ["create", "delete", "patch", "update"]
          - level: Metadata
            omitStages:
              - RequestReceived
          - level: RequestResponse
            userGroups: ["system:unauthenticated"]
      permissions: 0644
      path: /etc/kubernetes/audit-policy/audit-policy.yaml
      op: create