apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api-inference-extension/releases/download/v1.1.0/manifests.yaml
  - kserve-gateway.yaml

helmCharts:
- name: kserve-crd
  namespace: kserve
  repo: oci://ghcr.io/kserve/charts/kserve-crd
  version: 0.17.0
  releaseName: kserve-crd
- name: kserve-resources
  namespace: kserve
  repo: oci://ghcr.io/kserve/charts/kserve-resources
  version: 0.17.0
  releaseName: kserve
  valuesFile: values.yaml