kserve:
  controller:
    deploymentMode: Standard
    gateway:
      domain: ai.z3cyber.tech
      ingressGateway:
        enableGatewayApi: false
        kserveGateway: kserve/kserve-ingress-gateway
        createGateway: false
        gateway: knative-serving/knative-ingress-gateway
        className: istio
    nodeSelector: {}
    tolerations: []
    topologySpreadConstraints: []
    affinity: {}
    image: kserve/kserve-controller
    tag: ''
    imagePullSecrets: []
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi
    knativeAddressableResolver:
      enabled: false

