# smoke-test.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami
          imagePullPolicy: Always
          name: whoami
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-route
  namespace: whoami
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "whoami.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: whoami
        port: 80