nameOverride: "loki"
loki:
  auth_enabled: false
  image: 
    repository: 'zazathomas/cg-loki' 
    tag: 3.1.0
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  useTestSchema: false
  storage_config:
  filesystem:
    directory: /tmp/loki/
singleBinary:
  replicas: 1
deploymentMode: 'SingleBinary<->SimpleScalable' 
