nameOverride: "loki"
loki:
  auth_enabled: false
  image: 
    repository: 'zazathomas/cg-loki' 
    tag: 3.1.0
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem # we're storing on filesystem so there's no real persistence here.
      schema: v13
singleBinary:
  replicas: 1
deploymentMode: 'SingleBinary<->SimpleScalable' 
