---
apiVersion: v1
kind: Service
metadata:
  name: cockpit
  namespace: homelab-routes
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: cockpit
  namespace: homelab-routes
  labels:
    kubernetes.io/service-name: cockpit
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.5
ports:
  - name: http
    port: 9090
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cockpit-route
  namespace: homelab-routes
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "cockpit.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: cockpit
        port: 80