---
apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: homelab-routes
spec:
  ports:
  - name: http
    port: 8282
    protocol: TCP
    targetPort: 8282
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: openwebui
  namespace: homelab-routes
  labels:
    kubernetes.io/service-name: openwebui
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.10
ports:
  - name: http
    port: 8282
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui-route
  namespace: homelab-routes
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "webui.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: openwebui
        port: 8282