apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector-homelab
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: 9.0.322
    helm:
      releaseName: reflector
  destination:
    server: "https://141.148.61.125:6443"
    namespace: kube-system
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
#    syncOptions:
#      - CreateNamespace=false
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true
