#values.yaml
kubeProxyReplacement: true
namespace: "kube-system"
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: "10.244.0.0/16"

k8sServiceHost: "10.0.0.13" # This IP should be the IP of the control plane node
k8sServicePort: "6443"

# Enable Gateway API
gatewayAPI:
  enabled: true
  externalTrafficPolicy: Local
  #xffNumTrustedHops: 1
  
# Enable envoy
envoy:
  enabled: true
  rollOutPods: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
      - NET_BIND_SERVICE
      - CAP_NET_ADMIN
      - CAP_BPF

# Setup mutual authentication
authentication:
  mutual:
    spire:
      enabled: true
      install:
        enabled: true

encryption:
  enabled: true
  type: wireguard


# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 200
  
operator:
  replicas: 1  # Uncomment this if you only have one node
  rollOutPods: true
# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# Enable Hubble
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true