apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: core
    repoURL: https://neuvector.github.io/neuvector-helm
    targetRevision: 2.8.1
    helm:
      releaseName: neuvector
      valueFiles:
      - $values/K8s/OKE+Cilium/neuvector/values-oke.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: neuvector
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true

