# ArgoCD UI
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: neuvector-route
  namespace: neuvector
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "neuvector.z3cyber.pro"
  rules:
   - backendRefs:
      - name: argocd-server
        port: 80



      