apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-creds
  namespace: databases
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore # Must match SecretStore on the cluster
  target:
    name: r2-creds # Name for the secret on the cluster
    creationPolicy: Owner
  dataFrom:
    - extract: 
        conversionStrategy: Default	
        decodingStrategy: None
        key: r2-credentials # Key in the OCI Vault
        metadataPolicy: None

