apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api-inference-extension/releases/download/v1.1.0/manifests.yaml # Gateway API Inference Extension CRDs
  - https://raw.githubusercontent.com/envoyproxy/ai-gateway/v0.3.0/manifests/envoy-gateway-config/rbac.yaml # Gateway API rbac

helmCharts:
- name: aieg-crd
  namespace: envoy-ai-gateway-system
  repo: oci://docker.io/envoyproxy/ai-gateway-crds-helm
  version: v0.3.0
  releaseName: aieg-crd
- name: aieg
  namespace: envoy-ai-gateway-system
  repo: oci://docker.io/envoyproxy/ai-gateway-helm
  version: v0.3.0
  releaseName: aieg