apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: david-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ibinaiyedavid@gmail.com
    privateKeySecretRef:
      name: david-production
    solvers:
      - dns01:
          cloudflare:
            email: ibinaiyedavid@gmail.com
            apiTokenSecretRef:
              name: david-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "warp.d4rkcyber.xyz"
            - "*.warp.d4rkcyber.xyz"
