apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 70.8.0
    helm:
      releaseName: prometheus
  destination:
    server: "https://141.148.61.125:6443"
    namespace: monitoring
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true