apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts/'
    chart: loki
    targetRevision: 6.37.0
    helm:
      releaseName: loki
      valueFiles:
      - $values/K8s/homelab/applications/monitoring/loki_values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true