# Deployment mode: SingleBinary (simple), SimpleScalable (medium), Distributed (large)
deploymentMode: SingleBinary

# Number of replicas
singleBinary:
  replicas: 1
  extraArgs: [ "-config.expand-env=true" ]
  extraEnv:
    - { name: MINIO_ACCESS_KEY_ID, valueFrom: { secretKeyRef: { name: minio-credentials, key: MINIO_ACCESS_KEY_ID } } }
    - { name: MINIO_SECRET_ACCESS_KEY, valueFrom: { secretKeyRef: { name: minio-credentials, key: MINIO_SECRET_ACCESS_KEY } } }

# Component replicas
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
distributor:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
ruler:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0

# Caching
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Helm test
test:
  enabled: false

# All loki settings combined under one key
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  
  # Enable resources limits and requests
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin

    s3:
      endpoint: https://api-s3.local.z3cyber.tech
      accessKeyId: ${MINIO_ACCESS_KEY_ID}
      secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
      region: null
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: false


    tsdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h

  schemaConfig:
    configs:
      - from: "2025-06-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # Pattern ingester for better performance
  pattern_ingester:
    enabled: true
  
  # Configure limits for stability
  limits_config:
    max_query_parallelism: 16
    ingestion_rate_mb: 16 
    ingestion_burst_size_mb: 32 
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 72h # 3 days retention
    allow_structured_metadata: true
    volume_enabled: true
  
  compactor:
    retention_enabled: true
    delete_request_store: s3
    compaction_interval: 2h
    working_directory: /var/loki/compactor

  ingester:
    chunk_encoding: snappy