apiVersion: apps/v1
kind: Deployment
metadata:
  name:  stirling-pdf
  namespace: utilities
  labels:
    app:  stirling-pdf
spec:
  selector:
    matchLabels:
      app: stirling-pdf
  replicas: 1
  template:
    metadata:
      labels:
        app:  stirling-pdf
    spec:
      containers:
      - name: stirling-pdf
        image: stirlingtools/stirling-pdf:0.44.2
        resources:
          requests:
            cpu: 50m
            memory: 70Mi
          limits:
            cpu: 400m
            memory: 500Mi
        ports:
        - containerPort:  8080
          name:  http
        env:
        - name: TZ
          value: Europe/Dublin
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: utilities
spec:
  selector:
    app: stirling-pdf
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pdf-route
  namespace: utilities
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "pdf.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: stirling-pdf
        port: 8080