---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-client-secret
  namespace: ghost
spec:
  encryptedData:
    client-secret: AgA87WNNUH2WLaFkypfYuYTC9KCD83VhvTXF3TF7b3knl/r+HXkkeanYkzk3mwi2RV+QOelU7s7hpAmNyrQUtHXD3rRIv/AtIFydrJWDQtP2a/LLxU2y9v9p/UG3ev92eZB087XAYrPBGwEcpynC1UZpbFOnaRvfGeBsrxY5OJSEojQSZ+mLqtTv9FcpBWuHmI3EkOOG2MfDrchq542QC/maTe1S5JIrBDfU99/vVV9U/mMXCYkxd+esmpWrCaPJ8vxryqtv6E/MsPCkcHvGf8nATPi86izjygHwS5uZQICyLAK1J+J3O0g+f+TgYkCMsb1hdiiOUEHy5oNUfRm+zzLyyAVqRcx8lYLdvQ8OQ3DicBweB4el3VYnt+Gn/eocChtdZGkiqh79JBtPGt5rMh1lK86sqjzZuzluVkHLvB8M83zuYDA6f1id98knBvh5yLso8VGiaVghb2hHJJXwvNbKeVMxbsASSkcgrXy8eGy7FznwTsZLTL2zGFzXDFO2OGqhgtxVKfZj2ALuO02yxml6JNwTLYfmjPKmIWNjhDFVz3nBdBTRvK4kZ0YskF+9Ig/oLTyOBMnXDdMztNEYgNce/5CiaWwXmiN7RYdE645/vK9lVzyBag91+Gd8TvZL6pYuwHvOknQ5omiKxPEBxsikSybdM4pqmLLqxP/luEYgKQnV/hPOGOkikk5QkU55YCIfBfgsv/M8qlk8yg4qhJS6c4agQsaqWrM/OKqK/KW1bg==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-client-secret
      namespace: ghost
    type: Opaque
