services:
  searxng-valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    user: "1000"
    networks:
      - proxy
    volumes:
      - ./valkey_data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: searxng/searxng:2024.12.1-0245e82bd
    restart: unless-stopped
    user: "1000"
    networks:
      - proxy
    ports:
      - "8181:8080" #change 8181 as needed, but not 8080
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://192.168.0.32:8181 #Change "your.docker.server.ip" to your Docker server's IP
      - UWSGI_WORKERS=4 #You can change this
      - UWSGI_THREADS=4 #You can change this
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`search.local.z3cyber.tech`)"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
 
networks:
  proxy:
    external: true 
