apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage-route
  namespace: homepage
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "homepage.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: homepage
        port: 3000
        group: ''	
        kind: Service
        weight: 1	
     matches:	
        - path:	
            type: PathPrefix	
            value: /
