apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.7.26
    helm:
      releaseName: jenkins
      valueFiles:
      - $values/K8s/OKE+Cilium/jenkins/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jenkins
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true