# Keycloak
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jenkins-route
  namespace: jenkins
spec:
  parentRefs:
  - name: cilium-gw # gateway name
    namespace: gateway
  hostnames:
  - "jenkins.z3cyber.tech"
  rules:
  - backendRefs:
    - name: jenkins
      port: 8080
