apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  serviceName: "keycloak-service"
  replicas: 1 
  template:
    metadata:
      labels:
        app: keycloak 
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.6
          args: 
          - 'start'
          - "--db postgres"
          - "--db-url jdbc:postgresql://keycloak-db.databases.svc:5432/keycloak"
          - "--db-username keycloak"
          resources:
            requests:
              cpu: 100m
              memory: 498Mi
            limits:
              cpu: 500m
              memory: 600Mi
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db_password
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: hostname
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: TZ
              value: "Europe/Dublin"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: keycloak
  name: keycloak-service
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP