apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: databases
spec:
  description: "Keycloak DB"
  instances: 2
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak

  storage:
    storageClass: standard
    size: 2Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://pg-backups-oci/
      endpointURL: https://d4f626e53977981652bb18a0948b046c.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: r2-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: r2-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: "7d"

  resources:
    requests:
      memory: "256Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false