---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB32vDW6uF2TwKXRhp04kPhawzOJ3B0AOGhbz+ZimR6tvEPXX2WyzV9TYeJoya762PyTgohD/GkFM6PG9h75UlW/8+47iXkWe3nzKDPK+nXOE/zrjHpZ44Ih4D6eQfDVeGyDaK1KyjppjcPSeO8rYofQb3DCBmny8ZMncSa26h/6zikQVNDcGuqbCcPflfel27z6RJbv5k6JQP/mVXaWNFlwH9kEoq+gtWKyfQw32HnxyXJfeYh/WYEfZcWscka2h7CT0EwJQMyNvqO0jsCwrLxBKWbdVhhhSTpErzCnRUz4duuvecZ76iPuTqmo4ZSW2frodGSoJ6jtmyXDjBEXZdhzmW8awNBVNzkNFSQRlDMe3BEK4c0SI0fhFir8GwgJWnxD6owJ6FMvMmMk0W/9xfEu0l4LBOmziASEWpO1Zfi6ghwhN97VSRX0Ji76oWST3AN378Sk2U51rjF1B5tqLYJtNLeVtLK/zfEkXPBIrsfF2DeBJ/TIlrXxdxu4v+OwHbMARltuIoROy88yoJBtBLDNXcABqtcTRnERKfC9f59NwcPhpJD7oJ7rXX+/qo6mEiG2vPuXkOW1jOEjn17kpO1dgYZm8RwRp6a3Afl0gsfjYbrmowmhx4UGzrFMSuvIPMD12Trutx/rMFxuaKPLhqLuPS5BsqOnYj2KJjed9fwycBkuaURLSDl/cKjVuBaR4VogknanGjyaJNf7qXDblxQyewOZ9w=
    admin-user: AgBJttl2k+91fmqGxsvGacLuhHVj7VW1opfimO4DVitaIM31B4prMwxsKB8vDg6tO2KbRcauftR82VujUcMv0Fkpp9REgw2b3AKkAxQi027uaI7SRFJIdM9SW2FDsAvIoU4rpL1mQcm3ZWfmI5tTF7Z4IkGZMK3lU4gsOZIOMszPsWCdA++4Ps8M0qAEiZk8xGWCAgrGraV96eHvk0SJDqF1+3dCL0QrYjQLhzPanxdn/tC4Wwx9HOyiHUSGIwWcox9B80/wHYexeuPAFGKRni7ptEzAwQxR9x8P31UCZq/DFJSYgnxmZEYPcBaqhgNwEH8cQVKTz76iU3F43kVtMm+O8YeAMmzFpFUi6E/B3tRLmozeHjuyvQWKdyHpc3nWI/B4f+gHCK3GdTx8mDvQk5Mg1WswF6qcA8viEmonjW7s33N+T5yLliVoV4qzOZuNvh0rwIu4K5gjAkS5HivCK2k0xC4xnWYnQVjhKLmIoZCrj+EPYYfPKPi3OlDnipjidW9837YxDX8beuKZrsq+iKAMpB3hWyPBuUbusbJGuMZC3Dg5FozHMPa5atDhkkV3w0qT2h7agY3B6jpz9T/aIa3AHlPDjuHGb3krG7BXcdLtKJSHifuDVmF566oaZQBBMg5YkPznLZMWDq6CtuEj91J9ptsA4yuYfA7VMQDldDCNJdj5WrwA5QTElNIVMWuIVpRAfmiL8uOBkKtm
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
