apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  #finalizers:
   # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.2
    helm:
      releaseName: prometheus
      valueFiles:
      - $values/K8s/Manifests/kube-prometheus-stack/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
#    syncOptions:
#      - CreateNamespace=false
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true