apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'docker.io/envoyproxy'
    chart: gateway-helm
    targetRevision: v1.4.1
    helm:
      releaseName: envoy-gateway
      valueFiles:
      - $values/K8s/homelab/applications/envoy/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: envoy-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true