apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-client-secret
  namespace: gateway
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore
  target:
    name: gateway-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: gateway-secret
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None