apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - envoy.yaml
  - gatewayclass.yaml
  - envoy-gateway.yaml
  - http-redirect.yaml
  - detect-ip-policy.yaml
  - global-ratelimit-policy.yaml
  - gw-auth-policy.yaml
  - gw-client-secret.yaml
  - podmonitors.yaml
