---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pdf-route
  namespace: utilities
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
  hostnames:
  - "pdf.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: stirling-pdf
        port: 8080