---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: utilities
spec:
  selector:
    app: stirling-pdf
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080