---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Management:
    - Proxmox:
        href: https://proxmox.local.z3cyber.tech
        description: Hypervisor
        icon: proxmox.png
        widget:
            type: proxmox
            url: https://192.168.0.189:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
    - Portainer:
        href: https://portainer.local.z3cyber.tech
        description: Container Management
        icon: portainer.png
        widget:
            type: portainer
            url: http://192.168.0.32:9000
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Teleport:
        href: https://access.z3cyber.tech
        description: Identity Aware Proxy
        icon: teleport.png
    - Kamaji-Console:
        href: https://console.z3cyber.tech/ui
        description: Hosted Control Plane
        icon: https://kamaji.clastix.io/images/logo.png

- Automation:
    - Jenkins:
        href: https://jenkins.z3cyber.tech
        description: Automation Server
        icon: jenkins.png
    - Argocd:
        href: https://argocd.z3cyber.tech
        description: GitOps for Continuous Deployment
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/argo-cd.png
    - N8n:
        href: https://n8n.local.z3cyber.tech
        description: Workflow Automation
        icon: n8n.png
    - Codeserver:
        href: https://code.local.z3cyber.tech
        description: VScode in Browser
        icon: vscode.png

- Networking:
    - Adguard-01:
        href: https://dns.local.z3cyber.tech
        description: DNS Provider
        icon: adguard-home.png
        widget:
          type: adguard
          url: http://192.168.0.2
          username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Adguard-02:
        href: https://adguard.local.z3cyber.tech
        description: DNS Provider
        icon: adguard-home.png
        widget:
          type: adguard
          url: http://192.168.0.3
          username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
          password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Traefik:
        href: https://traefik.local.z3cyber.tech
        description: Reverse Proxy
        icon: traefik.png
        widget:
            type: traefik
            url: https://traefik.local.z3cyber.tech
            username: {{HOMEPAGE_VAR_TRAEFIK_USERNAME}} # optional
            password: {{HOMEPAGE_VAR_TRAEFIK_PASSWORD}} # optional
    - Adguard-Sync:
        href: https://sync-dns.local.z3cyber.tech
        description: DNS Provider
        icon: adguard-home.png
    - TPLink:
        href: https://tplink.local.z3cyber.tech
        description: Router
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQEbyJymhxFmY_oPOmHOu3LW7dcCqhzmjVIQ&s

- Utility:
    - Paperless-ngx:
        href: https://paperless.local.z3cyber.tech
        description: Document Archive
        icon: paperless-ngx.png
    - Stirling-pdf:
        href: https://pdf.k8s.z3cyber.tech
        description: PDF Operations
        icon: stirling-pdf.png
    - Firefox:
        href: https://ff.local.z3cyber.tech
        description: Local browser
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/firefox.png
    - Gotify:
        href: https://gotify.local.z3cyber.tech
        description: Notifications Server
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/gotify.png
    - Json-Crack:
        href: https://json.local.z3cyber.tech
        description: JSON Visualizer
        icon: https://github.com/AykutSarac/jsoncrack.com/raw/main/public/assets/192.png
    - searXNG:
        href: https://search.local.z3cyber.tech
        description: Search engine
        icon: searxng.png
    - Vikunja:
        href: https://vikunja.local.z3cyber.tech
        description: Project Management
        icon: vikunja.png
        widget:
            type: vikunja
            url: http://192.168.0.32:3456
            key: {{HOMEPAGE_VAR_VIKUNJA_KEY}}
            enableTaskList: false # optional, defaults to false
    - Hoarder:
        href: https://hoarder.local.z3cyber.tech
        description: Link Repository
        icon: hoarder.png
    - PasteBin:
        href: https://lesma.eu
        description: Paste bin
        icon: pastebin.png

- Monitoring:
    - Grafana:
        href: https://grafana.local.z3cyber.tech
        description: Dashboard Visualizer
        icon: grafana.png
        widget:
            type: grafana
            url: http://192.168.0.59:3000
            username: {{HOMEPAGE_VAR_GRAFANA_USER}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - Prometheus:
        href: https://prometheus.local.z3cyber.tech
        description: Metrics Store
        icon: prometheus.png
        widget:
            type: prometheus
            url: http://192.168.0.59:9090
    - Uptime-kuma:
        href: https://uptime.local.z3cyber.tech
        description: Service Monitor
        icon: uptime-kuma.png
        widget:
            type: uptimekuma
            url: http://192.168.0.32:3010
            slug: statuspageslug
   # - Upptime-Github:
    #    href: https://zazathomas.github.io/upptime-monitor/
    #    description: Service Monitor
     #   icon: https://avatars.githubusercontent.com/u/73812536?v=4
    - Speedtest:
        href: https://speedtest.local.z3cyber.tech
        description: Latency tests
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/speedtest-tracker.png
        widget:  
            type: speedtest  
            url: http://192.168.0.32:8045
            bitratePrecision: 3 #%20optional,%20default%20is%200

- Security:
    - Keycloak:
        href: https://sso.z3cyber.tech
        description: Identity Provider
        icon: keycloak.png
    - Akto:
        href: https://akto.local.z3cyber.tech
        description: API Security
        icon: https://avatars.githubusercontent.com/u/91220613?s=48&v=4
    - Neuvector:
        href: https://neuvector.z3cyber.tech
        description: Runtime Security
        icon: https://avatars.githubusercontent.com/u/19367275?s=200&v=4
    - WebCheck:
        href: https://webcheck.k8s.z3cyber.tech
        description: OSINT
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/web-check.png
    - JuiceShop:
        href: https://juiceshop.k8s.z3cyber.tech
        description: Security Testing
        icon: https://juice-shop.herokuapp.com/assets/public/images/JuiceShop_Logo.png

- Data:
    - Kopia-1:
        href: https://kopia-1.local.z3cyber.tech
        description: Disaster Recovery
        icon: kopia.png
        widget:
            type: kopia
            url: http://192.168.0.32:51515
            username: {{HOMEPAGE_VAR_KOPIA_USER}}
            password: {{HOMEPAGE_VAR_KOPIA_PASSWORD}}

    - Minio:
        href: https://minio.z3cyber.tech
        description: Object Storage
        icon: minio.png
    - Redpanda:
        href: https://redpanda.local.z3cyber.tech
        description: Message Broker
        icon: https://cdn.prod.website-files.com/6632a83042773c5a1a5f4443/6647694a827e35299ffead7f_redpanda-logo-red.svg
    - Pgadmin:
        href: https://pgadmin.local.z3cyber.tech
        description: Database Management
        icon: pgadmin.png


- Media:
    - Media-Calendar:
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            timezone: Europe/Dublin # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
            integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
                  service_group: Media # group name where widget exists
                  service_name: Sonarr # service name for that widget
    - Jellyfin:
        href: https://jellyfin.local.z3cyber.tech
        description: Media Server
        icon: jellyfin.png
        widget:
            type: jellyfin
            url: http://192.168.0.59:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_APIKEY}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - Jellyseerr:
        href: https://jellyseerr.local.z3cyber.tech
        description: Media Requester
        icon: jellyseerr.png
        widget:
            type: jellyseerr
            url: http://192.168.0.59:5055
            key: {{HOMEPAGE_VAR_JELLYSEERR_APIKEY}}
    - Radarr:
        href: https://radarr.local.z3cyber.tech
        description: Movies
        icon: radarr.png
        widget:
            type: radarr
            url: http://192.168.0.59:7878
            key:  {{HOMEPAGE_VAR_RADARR_APIKEY}}
            enableQueue: true # optional, defaults to false
    - Sonarr:
        href: https://sonarr.local.z3cyber.tech
        description: TV Shows
        icon: sonarr.png
        widget:
            type: sonarr
            url: http://192.168.0.59:8989
            key: {{HOMEPAGE_VAR_SONARR_APIKEY}}
            enableQueue: true # optional, defaults to false
    - Audiobookshelf:
        href: https://audiobooks.local.z3cyber.tech
        description: Audio Books
        icon: audiobookshelf.png
        widget:
            type: audiobookshelf
            url: http://192.168.0.59:13378
            key: {{HOMEPAGE_VAR_AUDIOBOOKSHELF_APIKEY}}
    - Readerr:
        href: https://readarr.local.z3cyber.tech
        description: Books
        icon: readarr.png
    - Prowlarr:
        href: https://prowlarr.local.z3cyber.tech
        description: Torrent Indexer
        icon: prowlarr.png
    - Qbit:
        href: https://qbit.local.z3cyber.tech
        description: Torrent Downloader
        icon: qbittorrent.png
