# ArgoCD UI
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: teleport-route
  namespace: argocd
spec:
  parentRefs:
  - name: cilium-gw
    namespace: cilium
  hostnames:
  - "teleport.z3cyber.pro"
  - "*.teleport.z3cyber.pro"
  rules:
   - backendRefs:
      - name: argocd-server
        kind: ExternalName
        port: 443