apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-oke-lb-service
spec:
  rules:
  - name: mutate-oke-lb-service
    match:
      resources:
        kinds:
        - Service
        namespaces:
        - gateway
    preconditions:
      all:
      - key: "{{ request.object.spec.type }}"
        operator: Equals
        value: "LoadBalancer"
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
            service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
            oci.oraclecloud.com/load-balancer-type: "lb"
