#values.yaml
kubeProxyReplacement: true
namespace: "kube-system"
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: "10.244.0.0/16"

k8sServiceHost: "10.0.0.4" # This IP should be the IP of the master node
k8sServicePort: "6443"

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 200

# Disable envoy
envoy:
  enabled: false
  
operator:
  replicas: 1  # Uncomment this if you only have one node
  rollOutPods: true
# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# Enable Hubble
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true