apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki+promtail-app
  namespace: argocd
  #finalizers:
   # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zazathomas/Homelab.git
    targetRevision: HEAD
    path: K8s/Manifests/loki+promtail
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
#    syncOptions:
#      - CreateNamespace=false
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true