---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-wg
  namespace: wg-easy
spec:
  type: ClusterIP
  ports:
    - port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    app.kubernetes.io/name: wg-easy
