# Wireguard UI
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wg-easy-ui
  namespace: wg-easy
spec:
  parentRefs:
  - name: cf-envoy-gw
    namespace: gateway
  hostnames:
  - "wg-cloud.z3cyber.tech"
  rules:
  - backendRefs:
      - name: wg-easy-http
        port: 51821