---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBe9M26juSfzk3cfTcFSKXrhBiZop3sJisLuK6GC0hggloK6GdM3apxaVXtg0SYnAJV8nF3NyNtRteCh41vHnXYGwA1ngHheaHWpwdxGhTi1lrc2C9S37ucM4U4HijXJgT3k/18pwMsxCy9wht9S6TqoPmnJ9ZfB3RjelacUjREmxvIojMjGCoDf4QQkXHx7FNZ2aAwbAsGvvpssUB19dKAdHI1jja3UyZiDG1Qj4VMuwvwZirJvPqBBd8UbVNGK21Pc4Us8cL9Dd5IrioEsmsboOQ2uyJ2VlNWNTfKEPJ3rzRPeDKPjYf1kdo1WiqKrm8dF0zE00xzroOvB6Y7OsOkDOJX4kaJLnnDzkSyu91379uUcjvDhplcJMn1VwivQst/7n07+2yHxCxdkdAFEjLkwBegbJ6cdcpdNrXjwaiU/kEOwPxlKzFATv1kgE40CERt0UD47tIy8tf27uyTSq8LUGZR1XpugThqWQe5D+YhX4TxXYhwglyjdHXcYQdkLj+5FAI0Of2kafVeE1qSGrFePwZQ/2GSDBSO3teqKJG9Nh3+hnlWD3ri+WLBgDMtQ3KqfVTLSUbj571UZy8MXLuq3ncg9eYdVuxFJYGbauURInljcEg5GyrMQhGvblY/tMzt+urn8TeEpMiIF7B+tK7+18cc9ZfQQ+gzNlnmbp9VC3TpeAa7TJNDKw5qcjBPeeUpilsYBxsuOsNXGczKGCyEQ/ylZFtx7FoeFh5zugewkNPfuS02qoCp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
