# ip-pool.yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.0.227"
      stop: "192.168.0.230"