image:
  repository: "zazathomas/cg-cilium"
  tag: "v1.16.0"
  useDigest: false

#values.yaml
k8sServiceHost: "192.168.0.39" # This IP should be the IP of the master node
k8sServicePort: "6443"
kubeProxyReplacement: true
namespace: "kube-system"
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"

# Announce IPs from services' `.status.loadbalancer.ingress` field (automatically assigned by LB-IPAM).
l2announcements:
  enabled: true

# Announce manually assigned IPs from services' `.spec.externalIPs` field
externalIPs:
  enabled: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 200
# Disable envoy
envoy:
  enabled: false
operator:
  # replicas: 1  # Uncomment this if you only have one node
  rollOutPods: true
  image:
    repository: "zazathomas/cg-cilium-operator"
    tag: "v1.16.0"
    useDigest: false
# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# Enable Hubble
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
    image:
      repository: "zazathomas/cg-cilium-hubble-relay"
      tag: "v1.16.0"
      useDigest: false
  ui:
    enabled: true
    rollOutPods: true
    backend:
      image:
        repository: "zazathomas/cg-cilium-hubble-ui-backend"
        tag: "v0.13.1"
        useDigest: false
    frontend:
      image:
        repository: "zazathomas/cg-cilium-hubble-ui"
        tag: "v0.13.1"
        useDigest: false