apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly-pm
  namespace: dragonfly-operator-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: dragonfly-cluster
  namespaceSelector:
    matchNames:
      - dragonfly-operator-system
  podMetricsEndpoints:
  - port: admin
    interval: 15s
    scheme: http
