---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly-auth
  namespace: dragonfly-operator-system
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore
  target:
    name: dragonfly-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: dragonfly-password
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None