---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCTg9ISw+1CmdYDzk+AQDCcJpyUknGz74Iu9ceRoxV8ZiL/PJ6ql5Wo9oq0wrfiQce2uidS8EAdP83KZW/bfkhxsvLlWXkKDYsQKq2ahzDpzoPzLl/Oozz1e2gaXvQX9Na5rkv499kGgL3PemAFRBMgEcWE74wMLVeKCLHVIo5hv+WZ+69oGwH1yYx+DlgVv004N7lqwLpNzUuBsRwA+C28GhE5zCQPjrkzcluHU6Z1Q3fBv8N6Z9YBEdohM6ghQSUG9WXN+orb38V40vnDpYhb2dajTGVYNLPPJ2JTXMBZPdoHRs3n0yXFN0Jt0WbkSEiHSCyPHGQEt0UrktdZJitg+9tR+K5gv05iVrcdcLMMvFo+IcSFIRack+wLp53zulED6u8KZEUJ+RuGIX8OIE+iU3Tb55/Vc1EmX+60PkfWZ1VEIVDByQesjtVksmKxWKOenzKhFI0ZDM5Kg5HeGzTXln8x8Oi258tiiwQ67YVz0SLCDj9U4nNdBAKtVr1ghgcy1x8IBusCxGrk6JdwsIfRUzhy9d468T+rpMZjMKNKwsAUpBhVa9iblyI2jBB74LRYWZUt+irjEMsPCO681B/dhNrWt38/PMvdbRkPwpDbF3TJ6pPJWSP4IjClTYRRgZvYNNV7xaIhU6JQNwdFe4kf39IqvmwdU4tISwBVsVtVbn2XvRL1Rd1I5Q+pqrHwO477vfPHBAXL1QHkFy3Lqjk6geM37FU06LjQU2DOOKsN9131d2HLmWF7
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
