apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.0
    helm:
      releaseName: sealed-secrets
      valueFiles:
      - $values/K8s/Manifests/sealed-secrets/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
#    syncOptions:
#      - CreateNamespace=false
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true

