---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCCYJ3pSdj4Fm3hzZ/sZmm/NwQl8OVH9N2rVvMbrMoyvKzNiFTc8gzb/ZnDNw92ez0geYl6Y2l++uZsYcJ1qSjZV7xxWzJhZCn/nSQUF35NmZEbvP0FSV8YaLPehj3x0Dl28mpcbAcKhSplbfaRSmN0RFM8nt2hLP2BV4i0MEBQIRy7tussEZQ9skKN3S3ImOD4RqRyFvD80aP90B5VuuKbvawrkcnPa1ZoyEERseay196LHGq2sHvIIrsVBi0RpdmY+0f1Shy8tSm4luZt9mj60oAU7UYtCNcTbtWb/uUmvGdmHjtwESLKfKjO93dyRtNOE+ltmrPlWPPYm5oHWv85bdStYu3FLivL8uNVRBDbQc2ZHUxIpBtVEpmVDXt1R4Lkmyj3cbycX1AWsqGfTDmrosFf29hl/wMk2KkzILSk2riaC5eyvbThioni+M/X+PcEfdnwHzY62159Uc+iniJ+iCba/MdfGs74xftWXV1grsLmJVfrYAktS3Y1twHWrU63ZNoUvfrTqYIq2DH7rsCAQvuP356Hx2sB0mV5o6wMh8usbBYD5PVbeA0gJejJXogVm1fIklRYh2GEVbVOUBDjwQbVRi+abNwyuswOAQ0yQqu4InxyurPi/1PhWapQAYkMyYOwd+BgnJivj6/gD3nmQeIQY+z8go6TXh7nVTZAaX91JFUdnLlxvRDgj7YQYBs47rW2kfz4uGXy14mJZpGlaa05Kb1XupEE9kpDdJ+4/G14Gz4o7q/N
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
