apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-homelab
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.17.1
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/K8s/homelab/applications/cert-manager/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://141.148.61.125:6443"
    namespace: cert-manager
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/zazathomas/Homelab.git'
    targetRevision: HEAD
    path: K8s/homelab/manifests/cert-manager
    directory:
      recurse: true
  destination:
    server: 'https://141.148.61.125:6443' 
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true