# ./rules/cloud/okta/okta_user_account_locked_out.yml
title: Find Tracing Policy Alerts
id: 14701da0-4b0f-4ee6-9c95-2ffb4e73bb9a
status: test
description: Detects when a tracing policy is triggered.
references:
    - https://developer.okta.com/docs/reference/api/system-log/
    - https://developer.okta.com/docs/reference/api/event-types/
author: Zaza Thomas
date: 2024/04/12
modified: 2024/04/21
tags:
    - attack.impact
logsource:
    product: tetragon
    service: runtime-sec
detection:
    keywords:
        - 'policy_name'
    condition: keywords
falsepositives:
    - Unknown
level: medium