title: Detect shell execution
id: 14701da0-4b0f-4ee6-9c95-2ffb4e73bb9a
status: test
description: Detects execution of a shell within a container.
references:
    - https://example.com
author: Zaza Thomas
date: 2024/04/21
modified: 2024/04/21
logsource:
    product: tetragon
    service: runtime-security
detection:
    selection:
        - Binary|endswith: /usr/bin/bash
        - Binary|endswith: /usr/bin/ash
        - Binary|endswith: /usr/bin/sh
    condition: selection
falsepositives:
    - Unknown
level: medium

# sigma convert -t loki -p pipeline.yaml rule.yaml -f ruler
