title: Find sudo
id: 14701da0-4b0f-4ee6-9c95-2ffb4e73bb9a
status: test
description: Detects when a tracing policy is triggered.
references:
    - https://developer.okta.com/docs/reference/api/system-log/
author: Zaza Thomas
date: 2024/04/21
modified: 2024/04/21
tags:
    - attack.impact
logsource:
    product: tetragon
    service: runtime-security
detection:
    selection:
        binary|contains: ls
    condition: selection
falsepositives:
    - Unknown
level: medium

# sigma convert -t loki -p pipeline.yaml rule.yaml
