apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared 
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore 
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json 
      remoteRef:
        key: cloudflared
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None