apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore # Must match SecretStore on the cluster
  target:
    name: example # Name for the secret on the cluster
    creationPolicy: Owner
  data:
    - secretKey: token # Key in the secret to be created
      remoteRef:
        key: cloudflare-token # Key in the OCI Vault