apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: external-secrets-podmonitor
  namespace: external-secrets
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics