apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
   - chart: cert-manager
     repoURL: https://charts.jetstack.io
     targetRevision: 1.15.1
     helm:
        releaseName: cert-manager
        valueFiles:
          - $values/K8s/Manifests/cert-manager/values.yaml
   - repoURL: https://github.com/zazathomas/Homelab
     targetRevision: HEAD
     ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
#    syncOptions:
#      - CreateNamespace=false
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true