apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: 8.3.7
    helm:
      releaseName: argocd
      valueFiles:
      - $values/K8s/OKE+Cilium/argocd.yml/argocd-values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true