# ArgoCD UI
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
  - name: cf-envoy-gw
    namespace: gateway
  hostnames:
  - "argocd.z3cyber.tech"
  rules:
  #- matches:
  #    - headers:
  #        - type: Exact
  #          name: allow-access
  #          value: zazilo
   - backendRefs:
      - name: argocd-server
        namespace: argocd
        port: 80