db:
  path: diun.db

watch:
  workers: 10
  schedule: "0 8 * * *"
  jitter: 30s
  firstCheckNotif: true
  runOnStartup: true

defaults:
  watchRepo: false
  notifyOn:
    - new
  sortTags: reverse
  maxTags: 3

notif:
  slack:
    webhookURL: https://hooks.slack.com/change-me-asap
    renderFields: true
    templateBody: |
      Patch Management Notification!
      A new image version for {{ .Entry.Image }} is now available. 
      Endeavor to update this image within the 3 weeks patch window where applicable.


providers:
  file:
    filename: /etc/diun/images.yaml
