---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAXNC64aJWW88DT0qISC4b0avoBCN4YbKH3d03f7PhNGWBlZl4uZt3G2VjArVrrXqQxAySoOiAo2rcyYY5nc7LlcClIeHpDyhTTcm6yZ1U0j9UdUd4MGZYzFRytbGjyfNbBMi0i/qnSf4r7iF5oaxTz1CjvFMWk+pNK+3i4NDOdN38wimsoTLLUzXXWhQnuOJgh5SDT/4Cn0Avet606LsMxvcEEhE4I4NNNkUR56eOOulBYzEEaW2vwCNqQn8ZCOulzKbLemV8FbMplaY0a/nYaOU5D+HWRLZfGLVz+Zma96xyfoAGLTEhIG2rrl94607RFmN1t3n4s2m0IpFeIjKkYo9ZGkfS00QOvEIxzIsWtx7oH0P7DgrLJEpejXQh3px72i9Z2FUqZs0Sr5VNGP7tqpTW0iM85OODClQaIx9XHxD9qZ66qtSGkNSiAdknQvaSuNpzI5+OEYWU1Cb+wfBhfd8FcJXXPrzKVVcf/6IM1b8/KHNkuO+22/rPnVLNHRp+ZGzycFU+A4drlpd461bUvjNUYkqIVlKkZOouQKvKbWYQiuWadaY8zWHYDM2XmP2kMC5JXcvJYqlZgOSm4/LPxlVKMMs8SVvO4w6N9TIYtKBIV6c3B4Dh5lmfac+RWxUmul76vuYzzTIIrtQFksC4V4T7vWpiNDrErpdp7OMINYKz4du1Gm1KbZOvqHGEBfGG2DKlvemF1ItXGcPhS0yI1Zx6A8Z2/Ig8wpgPbUhgq/95d80iWpL1Izs3XOg3JbWoC2IJQKgJcskyswRuDSGsSzZsTrCJUZyZmAYWlmHldzhtqe8984QtvMXd65+vouNyYdAA7F6ryYRDH3IbLRRLmHMxJ4eQjy/NSkpypnnPvhgsaYoHlphtvx91NkWaHpDbeu65+hRNpdXChNfinkgPBTQwucOF7hmbTghhuFH7P
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
