    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        tailscale.com/tailnet-fqdn: "infra-node.tailf76bc2.ts.net"
        tailscale.com/proxy-group: "tailscale-proxies"
      name: infra-node
      namespace: tailscale
    spec:
      externalName: placeholder # any value - will be overwritten by the operator
      type: ExternalName
      ports:
      - port: 22
        protocol: TCP