apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "teleport.tailf76bc2.ts.net"
    tailscale.com/proxy-group: "tailscale-proxies"
  name: teleport-vm   # service name
  namespace: tailscale
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ports:
    - port: 22
      protocol: TCP
