apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-route
  namespace: local-services
spec:
  parentRefs:
  - name: nlb-cilium-gw
    namespace: gateway
  hostnames:
  - "jellyfin.z3cyber.tech"
  rules:
   - backendRefs:
      - name: ts-intel-node-br8x2.tailscale.svc.cluster.local
        port: 8096
