---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-viewers-binding
  namespace: default
subjects:
- kind: Group
  name: k8s-readeronly
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view # Built-in read-only role
  apiGroup: rbac.authorization.k8s.io