---
apiVersion: v1
kind: Namespace
metadata:
  name: work-experience
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-learners-binding
  namespace: work-experience
subjects:
- kind: Group
  name: k8s-learners
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io