apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-configuration
  namespace: external-dns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore # Must match SecretStore on the cluster
  target:
    name: r2-creds # Name for the secret on the cluster
    creationPolicy: Owner
  dataFrom:
    - extract: 
        key: externaldns-credentials # Key in the OCI Vault

