apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-homelab
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://kubernetes-sigs.github.io/external-dns'
    chart: external-dns
    targetRevision: 1.15.2
    helm:
      releaseName: external-dns
      valueFiles:
      - $values/K8s/homelab/applications/external-dns/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://141.148.61.125:6443"
    namespace: external-dns
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true