---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: semaphore-db
  namespace: utilities
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  monitoring:
    enablePodMonitor: true

  nodeMaintenanceWindow:
    reusePVC: false

  #bootstrap:
    #recovery:
    #  backup:
    #    name: semaphore

  storage:
    size: 2Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://pg-backups-homelab/
      endpointURL: https://d4f626e53977981652bb18a0948b046c.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: r2-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: r2-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: "3d"

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "2"
  
  # externalClusters:
  # - name: semaphore-backup
  #   barmanObjectStore:
  #     destinationPath: s3://pg-backups-homelab/semaphore
  #     endpointURL: https://d4f626e53977981652bb18a0948b046c.r2.cloudflarestorage.com
  #     s3Credentials:
  #       accessKeyId:
  #         name: r2-creds
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: r2-creds
  #         key: ACCESS_SECRET_KEY

  # bootstrap:
  #   recovery:
  #     owner: keycloak
  #     secret:
  #       name: db-credentials
  #     database: keycloak
  #     backup:
  #       name: your-backup-resource-name

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-cluster-backup
spec:
  schedule: "0 3 * * *" # Daily at 3 AM
  cluster:
    name: pg-cluster
  backupOwnerReference: self
