apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/zazathomas/Homelab.git'
    targetRevision: HEAD
    path: K8s/homelab/manifests/homelab-routes
    directory:
      recurse: true
  destination:
    server: 'https://141.148.61.125:6443' 
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true
