apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app.kubernetes.io/appmanager: true
  #finalizers:
   # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zazathomas/Homelab.git
    targetRevision: HEAD
    path: K8s/Manifests/traefik/deployment
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
#    syncOptions:
#      - CreateNamespace=false
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true