apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: z3cyber-tech-cert
  namespace: gateway
spec:
  secretName: z3cyber-tech-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.z3cyber.tech"
  dnsNames:
  - "z3cyber.tech"
  - "*.z3cyber.tech"
  - "*.access.z3cyber.tech"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "gateway"  
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" 
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "gateway"