apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd_sso_secrets
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore
  target:
    name: argocd_sso_secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client_secret  # The key name ArgoCD wants
      remoteRef:
        key: argocd-secrets    # The name of the secret in OCI Vault
        property: client_secret # The specific JSON key INSIDE the OCI secret