configs:
  cm:
    oidc.config: |
      name: Keycloak
      issuer: https://sso.z3cyber.tech/realms/homelab
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

# kubectl -n argocd patch secret argocd-secret --patch='{"stringData": { "oidc.keycloak.clientSecret": "changeme" }}'