---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-client-secret
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgB+KZxqoMrhy8ZOAj8DrThiZaH7eU4+LW0fWNzgAnZLbCgZNjfjBnK5Kh9bgy9CeitxyJ8dI2ah2iK6CpB57wGx9WGmUJi5rZM0ahcXtx1XqObJbLreDhJ7AqNqRhFoP5RL111jMNk5+Ubx4U89FJI9NOoeGK1KRh9up+I/spbtY4ke6S66hTP0pCamg3ZncjvH0/my5w19ePoxaFSvCP+t8zrIL1JMUdgkTlP2mjQgDx0/Jve7czNiMrFwyEy28pHTMC6qlG4Y8PHXCQr8QOt4JKjK0nVoV9C2Wowxp5nk0cwWQ15Dvp2O6FkTRD4tsBwCFyIErna1oimU1lLyq2MRX0m6qrfSMhQwS7cWjaTgZKzBvTFu2zN/5GNs8MjwRQupFL0UjGX4zNmiYSRiNCXWIYofSjyW50tVtDVD8md5GVKaWvTOVp5TX2yTlhc6g2uMgINMXYkbs6VNYUvW9cnZ2QGXvLIl1MtneRqORXdcA2a8eEThSwwYf8S7B6uthEFZxoFTZ0Gw3A40dIHBBRd327sX4qYiGta/NeAFtSugB/RWHOdBLSXGrvhIbTUr/t+TqXy1V7/MRO9nMGaRSkahtR7o7UzkI4fLD9NtAsNHX9Opws/A7h6b1TVxl+L64d1koLMMLqzjIkrCCwrEmuEWteYGNGHGKUQNJu/ttZ0Jza7E5M8yCW7banfoIJ2weCgGcKO8XdNwmO+ob9NcdPaKgv7LeXlge1o4iwgEJVT2Pg==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-client-secret
      namespace: gateway
    type: Opaque
