---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-client-secret
  namespace: gateway
spec:
  encryptedData:
    client-secret: AgAxFQwsD0J5qlxZA+wlQDSqhLhyS3RF/IcVxzL+HvpgvFshPSFJeggimYrJKAQa9ZsuKHJybLgrVtCAaIwygqhcUIZyTGhVs6wxxfkrjceKa3OoLaT8aDVR5Fj9EB/L3dU3z2LHKu4PNd+g0dYmqcCt99b9i0elQw34gCrRemFuU+/Vj5OO+LK3BYlyneGFvzmgmtj5rqhdG/VAl6WA/4vBthhlpYyuuuU3jq2DsnYcLelao1GrvNofppRf1Np9eLsSFHVHZrx7+6Zzuvm5GSki4TiP2HsDDCo6+qzukka0Q+PIeUPq9t8Xw5ouCOMs33+L6eY9WVKw57oChDlx4xLFs9iWzYRfS3dhIyat5mFWjiV8zclo4/zxh5m97dkHTnPp9FoguhfjJ7eOWC739vAgm46/i0/jG2SHFAIhk6QdbkDdb7qFwf3ckUzeVAX0kdwgwb4fjHAWAHAF1thbldGRfW/3PSzkMdLGVTxnQCHpHOjOuaZzXZvu+X/C2N7RvV2mjQxLwOloZEyF9HUXKyjzSSNAGfi3TENY0KbqPhgMrfbBXM1mvgEHo07Vw01FImwt2KVcwjP00TNj5jqaB/dvOw7zYteM1Uy/Jr+q7dSy1s5ho6UVAlkvtVkU+uPPipb0I+MjfbgOUWZ5gcS14NGqhmIYAxJ1gDkKFo/44H4eB1YO9Z+iF9f+Qr10jXTDidWL4DolQfJxZkx8KmG9ke8bKd25G8PFnMt5Dik8NOpNmg==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-client-secret
      namespace: gateway
    type: Opaque
