apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - envoy.yaml
  - cf-detect-ip-policy.yaml
  - cf-envoy-gateway.yaml
  - cf-http-redirect.yaml
  - cf-ratelimit-policy.yaml
  - cf-gw-auth-policy.yaml
  - gatewayclass.yaml
  - gw-client-secret.yaml
  - nlb-envoy-gateway.yaml
  - nlb-http-redirects.yaml
  - nlb-ratelimit-policy.yaml
  - redis.yaml
  