apiVersion: apps/v1
kind: Deployment
metadata:
  name:  juiceshop
  namespace: pentesting
  labels:
    app:  juiceshop
spec:
  selector:
    matchLabels:
      app: juiceshop
  replicas: 1
  template:
    metadata:
      labels:
        app:  juiceshop
    spec:
      containers:
      - name:  juiceshop
        image:  bkimminich/juice-shop
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  3000
          name:  http
        env:
        - name: TZ
          value: Europe/Dublin
      restartPolicy: Always

