---
apiVersion: v1
kind: Service
metadata:
  name: webcheck
  namespace: pentesting
spec:
  selector:
    app: web-check
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000