---
  name: Checkov
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:
      
  jobs:
    checkov-scan:
      runs-on: ubuntu-latest
      permissions:
        # required for all workflows
        security-events: write
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8
        - name: Test with Checkov
          id: checkov
          uses: bridgecrewio/checkov-action@master
          with:
            directory: K8s/OKE+Cilium
            framework: kubernetes
          continue-on-error: true
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v3
          if: success() || failure()
          with:
            sarif_file: results.sarif
            category: checkov-scan