apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: external-routes
spec:
  ports:
  - name: app
    port: 5055
    protocol: TCP
    targetPort: 8096
  clusterIP: None
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: jellyseerr
  namespace: external-routes
  labels:
    kubernetes.io/service-name: jellyseerr
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.7
    conditions:
      ready: true
ports:
  - name: app
    port: 5055
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseerr-route
  namespace: external-routes
spec:
  parentRefs:
  - name: envoy-gw
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "jellyseerr.z3cyber.tech"
  rules:
   - backendRefs:
      - name: jellyseerr
        port: 5055
        group: ''	
        kind: Service
        weight: 1	
     matches:	
        - path:	
            type: PathPrefix	
            value: /