---
apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: external-routes
spec:
  ports:
  - name: http
    port: 8282
    protocol: TCP
    targetPort: 8282
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: openwebui
  namespace: external-routes
  labels:
    kubernetes.io/service-name: openwebui
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.10
ports:
  - name: http
    port: 8282
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui-route
  namespace: external-routes
spec:
  parentRefs:
  - name: cilium-gw
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "webui.k8s.z3cyber.tech"
  rules:
   - backendRefs:
      - name: openwebui
        port: 8282
        group: ''	
        kind: Service
        weight: 1	
     matches:	
        - path:	
            type: PathPrefix	
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openwebui-route-cf
  namespace: external-routes
  annotations:
    external-dns.alpha.kubernetes.io/controller: "ignore"
spec:
  parentRefs:
  - name: envoy-gw
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "chat.z3cyber.tech"
  rules:
   - backendRefs:
      - name: openwebui
        port: 8282
        group: ''	
        kind: Service
        weight: 1	
     matches:	
        - path:	
            type: PathPrefix	
            value: /